# Generated by Django 4.0.5 on 2022-08-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoder', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
