# Generated by Django 4.1 on 2022-08-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icoder', '0004_icodercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icodercomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icoder.icodercomment'),
        ),
    ]
