# Generated by Django 4.1 on 2022-09-03 12:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('icoder', '0005_alter_icodercomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icodercomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
