# Generated by Django 4.0.5 on 2022-09-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoder', '0006_alter_icodercomment_timestamp_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
